export const stepIndicatorStyles = {
    stepIndicatorSize: 50,
    currentStepIndicatorSize: 50,
    separatorStrokeWidth: 2,
    currentStepStrokeWidth: 2,
    stepStrokeCurrentColor: "#666666",
    stepStrokeWidth: 2,
    stepStrokeFinishedColor: "#ffa900",
    stepStrokeUnFinishedColor: "#666666",
    separatorFinishedColor: "#ffa900",
    separatorUnFinishedColor: "#666666",
    stepIndicatorFinishedColor: "#ffa900",
    stepIndicatorUnFinishedColor: "#666666",
    stepIndicatorCurrentColor: "#ffffff",
    stepIndicatorLabelFontSize: 13,
    currentStepIndicatorLabelFontSize: 13,
    stepIndicatorLabelCurrentColor: "#fe7013",
    stepIndicatorLabelFinishedColor: "#ffffff",
    stepIndicatorLabelUnFinishedColor: "#aaaaaa",
    labelColor: "#999999",
    labelSize: 13,
    currentStepLabelColor: "#fe7013",
    labelAlign: 'flex-start'
}