export const stepIndicatorLabels = [
    "Visita Técnica",
    "Visita técnica será realizada em breve", 
    "Visita técnica realizada", 
    "Dados da visita técnica em análise",
    "Escopo do Projeto Pronto",
    "Documentações",
    "Engenharia preparando documentações para solicitação de acesso junto a concessionária",
    "Engenharia com todas as informações em mãos",
    "Layout",
    "Engenharia está projetando seu sistema sob medida",
    "Enviado para sua aprovação",
    "Você aprovou",
    "Solicitação de Acesso",
    "Solicitação de acesso enviada para Distribuidora Local",
    "De acordo com o prazo regulatório, o limite para a concessionária analisar a solicitação de acesso é até:",
    "Solicitação de Acesso Aprovada",
    "Preparação dos Equipamentos",
    "Em separação",
    "Transporte dos Equipamentos",
    "Equipamentos em transferência",
    "Entrega dos Equipamentos",
    "Equipamentos entregues no seu local",
    "Instalação",
    "Consulte a franquia responsável pelo seu projeto sobre a data da Instalação",
    "Controle de Qualidade",
    "Equipe de instalação encaminhou fotos e relatórios",
    "Equipe de qualidade iniciou a análise técnica da instalação",
    "Seu projeto está certificado como qualidade máxima",
    "Vistoria",
    "Vistoria já foi solicitada para Distribuidora Local",
    "Vistoria Aprovada",
    "Troca do Relógio Medidor",
    "Relógio medidor trocado",
    "Gerando sua própria energia"
]

export const stepIndicatorLabelsFranchiseNext = [
    "Visita Técnica",
    "Visita técnica será realizada em breve", 
    "Visita técnica realizada", 
    "Dados da visita técnica em análise",
    "Escopo do Projeto Pronto",
    "Documentações",
    "Engenharia preparando documentações para solicitação de acesso junto a concessionária",
    "Engenharia com todas as informações em mãos",
    "Layout",
    "Engenharia está projetando seu sistema sob medida",
    "Enviado para sua aprovação",
    "Você aprovou",
    "Solicitação de Acesso",
    "Solicitação de acesso enviada para Distribuidora Local",
    "De acordo com o prazo regulatório, o limite para a concessionária analisar a solicitação de acesso é até:",
    "Solicitação de Acesso Aprovada",
    "Preparação dos Equipamentos",
    "Em separação",
    "Transporte dos Equipamentos",
    "Equipamentos em transferência",
    "Entrega dos Equipamentos",
    "Equipamentos entregues no seu local",
    "Instalação",
    "Preparando equipe, instalação será agendada em breve",
    "Agendada a instalação",
    "Instalação em andamento",
    "Instalação concluída",
    "Controle de Qualidade",
    "Equipe de instalação encaminhou fotos e relatórios",
    "Equipe de qualidade iniciou a análise técnica da instalação",
    "Seu projeto está certificado como qualidade máxima",
    "Vistoria",
    "Vistoria já foi solicitada para Distribuidora Local",
    "Vistoria Aprovada",
    "Troca do Relógio Medidor",
    "Relógio medidor trocado",
    "Gerando sua própria energia"
]